language: ruby
cache: bundler
rvm:
- 2.3.1

script: JEKYLL_ENV=production bundle exec jekyll build && bundle exec htmlproof --check-favicon --check-html ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
