# Setup
title:               Infomation Safety
tagline:             Improving technology through lessons from safety.
url:                 https://www.information-safety.org
paginate:            4
baseurl:             ""
permalink:           pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .bundle
  - .editorconfig
  - .git
  - .gitignore
  - .ruby-version
  - .travis.yml
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - bootstrap.sh
  - poole-LICENSE.md
  - tmp
  - vendor

sass:
  sass_dir:          _sass
  style:             :compressed

# Links to include in the masthead.
masthead_links:
  About:             '/about/'
  Blog:              '/'
  Resources:         '/resources/'
  Contribute:        '/contribute/'

# Disqus settings
disqus_url:          information-safety

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics:    UA-70082859-1

# poole custom vars prevent travis from working properly (invokes github-metadata)
# Custom vars
#version:             3.0.0
#github:
#  repo:              https://github.com/poole/poole
