# Exclude Travis CI vendor directory
exclude: [vendor]

# Permalinks
permalink:           pretty

# Setup
title:               Infomation Safety
tagline:             Improving information security through lessons from safety.
url:                 https://www.information-safety.org
paginate:            4
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Links to include in the masthead.
masthead_links:
  About:             '/about/'
  Blog:              '/'
  Resources:         '/resources/'
  Contribute:        '/contribute/'

# Disqus settings
disqus_url:          information-safety

# Google Analytics web tracking code
google_analytics:    UA-70082859-1

# poole custom vars prevent travis from working properly (invokes github-metadata)
# Poole Custom vars
#version:             2.0.0
#github:
#  repo:              https://github.com/poole/poole

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
