# Setup
title:               Information Safety
tagline:             Improving technology through lessons from safety.
url:                 https://www.information-safety.org
paginate:            3
baseurl:             ""
permalink:           pretty
notice: >
  Interested in applying lessons from safety to security?
  Learn more at [security-differently.com](https://www.security-differently.com)!

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate

# Optimize Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - bootstrap.sh
  - clean.sh
  - poole-LICENSE.md
  - poole-sass.patch
  - tmp
  - vendor

sass:
  sass_dir:          _sass
  style:             compressed

# Links to include in the masthead.
masthead_links:
  About:             '/about/'
  Blog:              '/'
  Resources:         '/resources/'
  Archive:           '/archive/'

# Disqus settings
disqus_url:          information-safety

# Options

# Replace this value and uncomment to enable Google Analytics tracking
#google_analytics:    UA-70082859-1

# poole custom vars prevent builds from working properly (invokes github-metadata) - see https://github.com/jekyll/jekyll/issues/4705
# Custom vars
#version:             3.0.0
