# Exclude Travis CI vendor directory
exclude: [vendor]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks no longer work in Jekyll v3
#relative_permalinks: true

# Setup
title:               Infomation Safety
tagline:             Improving information security through lessons from safety.
url:                 http://www.information-safety.org
paginate:            4
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Links to include in the masthead.
masthead_links:
  About:             '/about/'
  Blog:              '/'
  Resources:         '/resources/'
  Contribute:        '/contribute/'

# Disqus settings
disqus_url:          information-safety

# Google Analytics web tracking code
google_analytics:    UA-70082859-1

# github-metadata setting
repository: information-safety/information-safety.github.io

# Poole Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
