# Built from: https://github.com/actions/starter-workflows/blob/main/ci/ruby.yml and
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: ruby

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
      with:
        bundler-cache: true

    # from https://github.com/gjtorikian/html-proofer/blob/main/README.md#caching-with-continuous-integration
    - name: Cache HTMLProofer
      id: cache-htmlproofer
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: tmp/.htmlproofer
        key: ${{ runner.os }}-htmlproofer

    - run: bundle config set --local with ci
    - run: bundle install
    - run: bundle exec rake
